### ISSUE TITLE
working but printing error messages

### ISSUE THREAD

**Issue by 4zv4l** [UltiRequiem/coc-zig#4]
Hi,
When I install `coc-zig` it tells me that it cannot find zls executable and that I have to set the path in the config.
So I did `:CocConfig` to get the config file and I added the path but it still doesn't work.
![image](https://user-images.githubusercontent.com/46655455/165045324-d8149dce-4be6-4e42-93ce-ea777ab5d4f7.png)
Any idea ?

**Comment by 4zv4l** [comment]
just realized the extension works but still get that error message anyway
so the completion works but it still tells me that it cannot find zls

**Comment by UltiRequiem** [comment]
Could you give me the output of `:CocInfo`?

**Comment by UltiRequiem** [comment]
Closed due to inactivity and because I can't replicate it.
